version: "3.9"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=parthiba
      # - MONGO_INITDB_ROOT_PASSWORD=rono
    env_file:
      - ./env/mongo.env
    # It's mean create a env folder in the same folder of this compose.yaml file and create mongo.env file under that env folder ..
  backend:
    build: ./backend
    # build: 
    #   context: ./backend
    #   dockerfile: Dockerfile
        # args:
        #   some-arg: value
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./env/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
    
volumes:
  data:
  logs: